"""empty message

Revision ID: 309871a085e6
Revises: fe9d2ab7e00f
Create Date: 2020-03-05 18:18:16.598963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309871a085e6'
down_revision = 'fe9d2ab7e00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
